### ISSUE TITLE
Feature request: Message footer

### ISSUE THREAD

**Issue by azurecurve** [TukuToi/tukutoi-contact-form#3]
I'd like to be able to have a custom footer appended to the bottom of sent messages.

I use contact forms to email both myself and my employer depending on which form is used and I'd like to be vey clear when a message has come from my site to my employer.

**Comment by smileBeda** [comment]
This opens also the question of several forms in the same page, which I didn’t account for (given a contact form usually is a standalone instance, but … there’s no way that’s how users see it 😅)

so I’ll likely have to make a form ID (since classes for error management also are just generic at the moment and would apply to all forms in said page)

I’ll open a separate ticket for that

**Comment by smileBeda** [comment]
This has been made possible thru a hook (filtering the message depending on form ID)
This is documented in the new readme and should be working fine by now.

**Comment by azurecurve** [comment]
I tried with the below add_filter in my functions.php and the email doesn't send:
```
add_filter('tkt_cntct_frm_message', 'append_to_message', 10, 3);
function add_footer( $message, $form_fields, $receiver ){
	if( (int)$form_fields['id'] === 1 ){
		return $message . '<p>appended string</p>';
	}else{
		return $message;
	}
}
```

The shortcode was:
```
[tkt_cntct_frm_contact_form id=1]
```
As soon as I remove the filter, the email again sends.

**Comment by smileBeda** [comment]
I think the callback is invalid (`append_to_message` is called but `add_footer ` is declared)

Correct code:
```
add_filter('tkt_cntct_frm_message', 'append_to_message', 10, 3);
function append_to_message( $message, $form_fields, $receiver ){
	if( (int)$form_fields['id'] === 1 ){
		return $message . '<p>appended string</p>';
	}else{
		return $message;
	}
}
```

Fixed it in the readme.

**Comment by azurecurve** [comment]
Yeah, that was the issue.

However, that gives me this output when my message was "test 6":
```
test 6

IP: 84.92.40.217appended string
```
My appended message should be before the IP and the html should be present.

**Comment by smileBeda** [comment]
I strip the HTML.
This is a sanitize_text_area filtered content - both for the user facing message as well as for the filter.

The string is appended... because if I prepend it to the IP, then the I bet another user will want to append.

---

Possible solutions:
1. Do you think I should wp_kses_post the filtered content instead of sanitize_text_area?
I fear users will add HTML without CSS and then the email wont render it. That is why I strip it, also, apart of safety.
Additionally wp_kses_post won't allow for _all_ HTML so the next issue will be "but why does this not work when that works".
So I just chose to be restrictive, rather than liberal :P

2. About the appending, we have several options here.. considering there _will_ be the request to append (at the very end), I think splitting the vars provided by the filter, providing both message + IP as separate things, could help.
Then you can recompose as you want and append, prepend or mid-pend

Would that help?

**Comment by smileBeda** [comment]
I fiddled a bit with it.
The filter still would work the same, but now only filter the actual "sent message" (as from the user input)
Thus if you app- or prepend it will act on the actual message.

You can use HTML as allowed bu wp_kses_post in it (in your filter, not in the form field as logged out person, of course)

It also uses text/html as header now in the email

Additionally there is also a filter to control he IP line which if returned empty would remove the IP part, otherwise it just appends it last (not yet documented)

I quickly tested it and should work, however again late here, will probably have missed something.

**Comment by smileBeda** [comment]
Re-tested and updated readme as well.
Pushed everything to master branch, IMO ready to go.
