### ISSUE TITLE
Bug: Email sends again if page refreshed

### ISSUE THREAD

**Issue by azurecurve** [TukuToi/tukutoi-contact-form#4]
If a message is submitted and then the user refreshes the page, a duplicate message is sent.

**Comment by smileBeda** [comment]
One option is I use redirect with url parameters and/or redirect to target page, the other option is use session_start…

i think I’ll add a redirect attribute inside the shortcode to let the user choose a url target or a success message (which will however append an url parameter)

On it

**Comment by smileBeda** [comment]
This _should_ be fixed in develop branch. Note however that I had to break version to 2.x

This because (long story short) you cannot resolve the problem reported here while having a receiver email set in a shortcode (or for that is, a redirect)
These things happen on separate hooks and when we render shortcodes (and their attributes) it is too late to redirect, however redirect is needed to solve the problem, and redirect is only possible on another hook (such as template_redirect), which is way too soon to read off data from a ShortCode attribute.

The other possibility would have been to simply ignore this since a proper warning is actually shown to the user by the browser, since this is actual default behaviour of PHP forms. But, that is not nice. A third option would have been AJAX, but then you expose the receiver email in the request, unless of course we would start using options which requires a Menu with settings in the backend.

--- 

For keeping it _simple_, the receiver email defaults to the admin email now. If that should change, a filter has been added where the email can be changed (depending on form ID)/.
That allows me to properly redirect and thus avoiding this "sent twice" issue.

I am still testing, but it _should_ work. Readme in develop branch is updated with new approaches to take.

**Comment by smileBeda** [comment]
@azurecurve - I am closing here, this seems to be resolved (in _develop_ branch)
Note, if you fill the form incompletely, and reload the page, then the warning will still be there. But that I cannot do much about.
Also if someone fills the form without filling it out at all, and reloads the page, the warning still will happen
But also, no email will be sent, in those cases.

When however the form was submitted successfully it now has a proper redirect and reloading the page will just keep showing the success message, without resending the mail/warning or else incommoditities.

Feel free to comment/reopen if this isn't working for you.
